name: Mirror Specs
on:
  schedule:
    - cron: '22 3 * * *'
jobs:
  sync-specs:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        source-repo: "git@github.com:CocoaPods/Specs.git"
        destination-repo: "git@gitee.com:captain9911/DCSpecs.git"
