name: Mirror Specs
on: [push]

# on:
#   schedule:
#     - cron: '22 * * * *'
jobs:
  sync-specs:
    runs-on: ubuntu-latest
    steps:
#     - name: Sync to Gitee
#       uses: wearerequired/git-mirror-action@master
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
#       with:
#         source-repo: "git@github.com:CocoaPods/Specs.git"
#         destination-repo: "git@gitee.com:captain9911/DCSpecs.git"

      - name: Mirror with force push
        uses: Yikun/hub-mirror-action@master
        with:
          src: CocoaPods/Specs
          dst: captain9911/DCSpecs
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
